[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen = { version = "0.5.0", default_features = false }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
target = { path = "../service.wit" }